[package]
name = "nexo-csv"
version = "0.1.0"
edition = "2024"

[dependencies]
ring = "0.17"
# async, web
# data, serde, formats
serde.workspace = true
csv = "^1.3"
chrono.workspace = true
# errors, logs
snafu.workspace = true
# own libs
utils.workspace = true

[dev-dependencies]
anyhow.workspace = true
